//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store_ASP.NET_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public int Stars { get; set; }
        public string Subject { get; set; }
        public string Comment { get; set; }
        public string UserName { get; set; }
        public int ProductId { get; set; }

        public Review()
        {
            Id = -1;
            Stars = 0;
            Comment = "";
            Subject = "";
        }
    }
}
